name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"

jobs:
  update-readme:
    name: Update WakaTime stats in README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: wakatime_stats
          COMMIT_MESSAGE: Update README with new WakaTime metrics
